### ISSUE TITLE
[iommi 6.4] no longer accepts non-integer Primary Keys

### ISSUE THREAD

**Issue by jedrus2000** [iommirocks/iommi#493] opened 2023-12-14 11:36 UTC
My case is that I got data from JSONs, from third party service, and blindly accepted data ID of UUID4 into tables Primary Key type.

Error: 

![image](https://github.com/iommirocks/iommi/assets/22714418/8863d657-fe68-46d5-8a03-d19d3910f32a)

If it is kind of trade off, and `won't fix issue` then I suggest making error message more informative:

`f'Could not interpret {value_string_or_filter_name} as an integer. Only integer type Primary Key is supported.'`

Code point making error message:

https://github.com/iommirocks/iommi/blob/master/iommi/query.py#L992

**Comment by jlubcke** [comment] 2024-03-27 09:33
Duplicate of #523

**Closed** 2024-03-27 09:33 UTC
