### ISSUE TITLE
The thead on Table should be targetable for `attrs`

### ISSUE THREAD

**Issue by boxed** [iommirocks/iommi#578] opened 2024-09-28 06:39 UTC
The only way to set a css class on `<thead>` now is to override `table_header_rows.html`. 

From https://chaos.social/@apollo13/113211377039987429

**Comment by boxed** [comment] 2024-09-28 09:18
...and the `<tr>`s inside too

**Comment by apollo13** [comment] 2024-09-28 20:49
The `<tr>` thing is probably a dupe of #510

**Comment by boxed** [comment] 2024-09-30 14:08
#582

**Closed** 2024-09-30 15:34 UTC
